services:
  postgres:
    image: postgres:16
    container_name: sagepick_postgres_backend
    restart: always
    env_file: ./env/postgres.backend.env
    volumes:
      - ./data/postgres_backend:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - sagepick-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: sagepick_pgadmin
    restart: always
    env_file: ./env/pgadmin.env
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - sagepick-net

  # ------------------------
  # REDIS
  # ------------------------
  redis:
    image: redis:7
    container_name: sagepick_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    networks:
      - sagepick-net

networks:
  sagepick-net:
    driver: bridge
